openapi: 3.0.0
info:
  contact:
    email: contact@gamytech.com
  description: Provide client ids for companies in order to use properitary auth and
    cash flow
  title: Client Id Provider
  version: 1.0.0
servers:
- url: http://localhost:3000
- url: http://auth-provider.gamy-tech.com
tags:
- name: Accounts
paths:
  /accounts:
    post:
      description: Will create a new account for the bridge server
      operationId: createNewAccount
      requestBody:
        content:
          application/json:
            examples:
              JSON:
                value:
                  firstname: string
                  lastname: string
                  company_name: string
                  email: user@example.com
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "201":
          content:
            application/json:
              examples:
                JSON:
                  value:
                    id: 0
                    firstname: string
                    lastname: string
                    email: user@example.com
                    company_name: string
                    client_id: string
              schema:
                $ref: '#/components/schemas/Account'
          description: Created
      summary: Sign up to the gamytech bridge platform
      tags:
      - Accounts
      x-swagger-router-controller: Accounts
      x-eov-operation-handler: controllers/AccountsController
  /accounts/{id}:
    get:
      description: Get a company account by id
      operationId: getAccountById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                JSON:
                  value:
                    id: 0
                    firstname: string
                    lastname: string
                    email: user@example.com
                    company_name: string
                    client_id: string
              schema:
                $ref: '#/components/schemas/Account'
          description: OK
      summary: Get by id
      tags:
      - Accounts
      x-swagger-router-controller: Accounts
      x-eov-operation-handler: controllers/AccountsController
components:
  schemas:
    Account:
      example:
        firstname: firstname
        company_name: company_name
        id: 0.8008281904610115
        email: ""
        client_id: client_id
        lastname: lastname
      properties:
        id:
          type: number
        firstname:
          type: string
        lastname:
          type: string
        email:
          format: email
          type: string
        company_name:
          type: string
        client_id:
          type: string
      required:
      - client_id
      - company_name
      - email
      - firstname
      - id
      - lastname
      title: Account
      type: object
      x-examples:
        JSON:
          id: 0
          firstname: string
          lastname: string
          email: user@example.com
          company_name: string
          client_id: string
    body:
      properties:
        firstname:
          type: string
        lastname:
          type: string
        company_name:
          type: string
        email:
          format: email
          type: string
      required:
      - company_name
      - email
      - firstname
      - lastname
      type: object
  securitySchemes: {}
